sudo: false

language: python

python:
  - "3.6"
  - "3.7"

install:
  - pip install -e .
  - pip install pytest pytest-aiohttp pytest-cov coveralls

script:
  - py.test --cov=queueueue

after_success:
  - coveralls
