sudo: false

language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip install -e .
  - pip install pytest pytest-aiohttp pytest-coverage coveralls

script:
  - py.test --cov=queueueue

after_success:
  - coveralls
